# Generated by Django 4.0.4 on 2022-06-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agedetect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_data',
            name='input_image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='search_data',
            name='output_image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
